language: objective-c
osx_image: xcode7.3

xcode_project: CuckooAlert.xcodeproj

env:
        global:
                - FRAMEWORK_NAME=CuckooAlert
before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
before_script:
        - carthage bootstrap
before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: "FILE TO UPLOAD"
        skip_cleanup: true
        on:
                tags: true
